version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: mkwwmcp-redis
    command: redis-server --requirepass redispass --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
