global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@mkww.io'
  smtp_auth_username: 'alerts@mkww.io'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together.
  group_by: ['alertname', 'severity']
  
  # When a new group of alerts is created by an incoming alert, wait at least 'group_wait' to send
  # the initial notification. This way ensures that you get multiple alerts for the same group that
  # start firing shortly after another are batched together on the first notification.
  group_wait: 30s
  
  # When the first notification was sent, wait 'group_interval' to send a batch of new alerts
  # that started firing for that group.
  group_interval: 5m
  
  # If an alert has successfully been sent, wait 'repeat_interval' to resend them.
  repeat_interval: 3h 
  
  # A default receiver
  receiver: 'slack'
  
  # All the above attributes are inherited by all child routes and can overwritten on each.
  routes:
  # Critical alerts go to the on-call team
  - match:
      severity: critical
    receiver: 'on-call'
    continue: false
    
  # Warnings go to the dev team
  - match:
      severity: warning
    receiver: 'dev-team'
    continue: false

# Receivers
receivers:
- name: 'null'
  
- name: 'slack'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts'
    title: '{{ template "slack.mkww.title" . }}'
    text: '{{ template "slack.mkww.text" . }}'
    title_link: '{{ template "slack.mkww.titlelink" . }}'
    send_resolved: true
    
- name: 'on-call'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_ONCALL}'
    channel: '#on-call'
    title: '{{ template "slack.mkww.title" . }}'
    text: '{{ template "slack.mkww.text" . }}'
    title_link: '{{ template "slack.mkww.titlelink" . }}'
    send_resolved: true
    
  pagerduty_configs:
  - routing_key: '${PAGERDUTY_ROUTING_KEY}'
    description: '{{ .CommonAnnotations.summary }}'
    details:
      firing: '{{ template "pagerduty.mkww.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'

- name: 'dev-team'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_DEV}'
    channel: '#dev-alerts'
    title: '{{ template "slack.mkww.title" . }}'
    text: '{{ template "slack.mkww.text" . }}'
    title_link: '{{ template "slack.mkww.titlelink" . }}'
    send_resolved: true

# Templates
templates:
- '/etc/alertmanager/templates/*.tmpl'
